import type { FrameworkDefinition } from '../types/framework';

export const FW: Record<string, FrameworkDefinition> = {
  CJIS: {
    id: 'CJIS',
    label: 'CJIS',
    full: 'Criminal Justice Information Services Security Policy',
    desc: 'FBI CJIS Security Policy — required for any vendor with access to criminal justice information.',
    src: 'https://le.fbi.gov/file-repository/cjis-security-policy-v5-9-5-20240123.pdf',
    controls: [
      {
        id: 'cjis-1',
        sec: '5.1',
        label: 'Security Awareness Training',
        ref: 'Annual CJIS training required for all personnel with CJI access',
      },
      {
        id: 'cjis-2',
        sec: '5.2',
        label: 'Security Policy Agreement',
        ref: 'Signed acknowledgment of CJIS security policy requirements',
      },
      { id: 'cjis-3', sec: '5.3', label: 'Incident Response Plan', ref: 'Documented IR plan covering CJI breaches' },
      {
        id: 'cjis-4',
        sec: '5.4',
        label: 'Auditing and Accountability',
        ref: 'Audit logs of all CJI access — confirm retention with CSA',
      },
      {
        id: 'cjis-5',
        sec: '5.5',
        label: 'Access Control',
        ref: 'Role-based access, least privilege, need-to-know basis',
      },
      {
        id: 'cjis-6',
        sec: '5.6',
        label: 'Identification and Authentication',
        ref: 'Unique user IDs, MFA for remote access, strong password policy',
      },
      {
        id: 'cjis-7',
        sec: '5.7',
        label: 'Configuration Management',
        ref: 'Documented baseline configurations, change management process',
      },
      {
        id: 'cjis-8',
        sec: '5.8',
        label: 'Media Protection',
        ref: 'Encryption of CJI on all removable media, secure disposal',
      },
      {
        id: 'cjis-9',
        sec: '5.9',
        label: 'Physical Protection',
        ref: 'Restricted physical access to systems processing CJI',
      },
      {
        id: 'cjis-10',
        sec: '5.10',
        label: 'Systems and Communications',
        ref: 'FIPS 140-2/3 validated encryption in transit and at rest',
      },
      {
        id: 'cjis-11',
        sec: '5.11',
        label: 'Formal Audits',
        ref: 'Biennial CJIS compliance audit by authorized agency',
      },
      {
        id: 'cjis-12',
        sec: '5.12',
        label: 'Personnel Security',
        ref: 'Personnel screening requirements — confirm scope with CSA',
      },
    ],
  },
  FedRAMP: {
    id: 'FedRAMP',
    label: 'FedRAMP',
    full: 'Federal Risk and Authorization Management Program',
    desc: 'NIST 800-53 based cloud security framework required for federal government cloud services.',
    src: 'https://www.fedramp.gov/documents/',
    controls: [
      {
        id: 'fr-1',
        sec: 'AC-1',
        label: 'Access Control Policy',
        ref: 'Documented access control policy and procedures',
      },
      {
        id: 'fr-2',
        sec: 'AC-2',
        label: 'Account Management',
        ref: 'Formal account management, regular access reviews',
      },
      { id: 'fr-3', sec: 'AU-2', label: 'Audit Events', ref: 'Organization-defined auditable events logged' },
      {
        id: 'fr-4',
        sec: 'AU-9',
        label: 'Protection of Audit Info',
        ref: 'Audit logs protected from unauthorized modification',
      },
      {
        id: 'fr-5',
        sec: 'CA-3',
        label: 'System Interconnections',
        ref: 'Documented interconnection agreements for federal data flows',
      },
      {
        id: 'fr-6',
        sec: 'CM-6',
        label: 'Configuration Settings',
        ref: 'Secure baseline configurations established and maintained',
      },
      {
        id: 'fr-7',
        sec: 'IA-2',
        label: 'MFA for Privileged Users',
        ref: 'Multi-factor authentication for all privileged and remote access',
      },
      {
        id: 'fr-8',
        sec: 'IR-4',
        label: 'Incident Handling',
        ref: 'Incident handling with timely US-CERT notification',
      },
      {
        id: 'fr-9',
        sec: 'RA-5',
        label: 'Vulnerability Scanning',
        ref: 'Regular scans, more frequent for high-value assets',
      },
      {
        id: 'fr-10',
        sec: 'SC-28',
        label: 'Protection at Rest',
        ref: 'FIPS 140-2/3 validated encryption for federal data at rest',
      },
      {
        id: 'fr-11',
        sec: 'SI-2',
        label: 'Flaw Remediation',
        ref: 'Critical flaws patched promptly per FedRAMP baseline',
      },
      {
        id: 'fr-12',
        sec: 'ATO',
        label: 'Authority to Operate',
        ref: 'Valid FedRAMP ATO or equivalent authorization on file',
      },
    ],
  },
  StateRAMP: {
    id: 'StateRAMP',
    label: 'StateRAMP',
    full: 'State Risk and Authorization Management Program',
    desc: 'State-level cloud security framework for vendors serving state and local government agencies.',
    src: 'https://stateramp.org/resources/',
    controls: [
      { id: 'sr-1', sec: 'SR-AC-1', label: 'Access Control', ref: 'Documented state-level access control policy' },
      { id: 'sr-2', sec: 'SR-AC-2', label: 'Account Management', ref: 'Formal account lifecycle management process' },
      {
        id: 'sr-3',
        sec: 'SR-IA-1',
        label: 'Authentication Policy',
        ref: 'Authentication policy aligned to StateRAMP baseline',
      },
      {
        id: 'sr-4',
        sec: 'SR-IA-2',
        label: 'MFA Enforcement',
        ref: 'MFA required for all privileged and remote access',
      },
      {
        id: 'sr-5',
        sec: 'SR-IR-1',
        label: 'Incident Response',
        ref: 'Documented IR plan, state agency notification procedures',
      },
      { id: 'sr-6', sec: 'SR-CA-1', label: 'Security Assessment', ref: 'Annual third-party security assessment' },
      {
        id: 'sr-7',
        sec: 'SR-SC-1',
        label: 'Encrypted Communications',
        ref: 'TLS 1.2 or higher for all data in transit',
      },
      {
        id: 'sr-8',
        sec: 'SR-AU-1',
        label: 'Audit Logging',
        ref: 'Centralized log collection — confirm retention with CSA',
      },
      {
        id: 'sr-9',
        sec: 'SR-CM-1',
        label: 'Configuration Management',
        ref: 'Hardened baselines, documented change control',
      },
    ],
  },
  CISA: {
    id: 'CISA',
    label: 'CISA CPG',
    full: 'CISA Cross-Sector Cybersecurity Performance Goals',
    desc: 'CISA baseline cybersecurity performance goals for critical infrastructure and government contractors.',
    src: 'https://www.cisa.gov/cross-sector-cybersecurity-performance-goals',
    controls: [
      {
        id: 'cisa-1',
        sec: 'CPG 1.A',
        label: 'Phishing-Resistant MFA',
        ref: 'Phishing-resistant MFA on all internet-facing systems',
      },
      { id: 'cisa-2', sec: 'CPG 1.B', label: 'MFA for Email', ref: 'MFA enforced on all email accounts' },
      {
        id: 'cisa-3',
        sec: 'CPG 1.C',
        label: 'Strong Password Policy',
        ref: 'Passwords 15+ characters, no complexity requirement',
      },
      {
        id: 'cisa-4',
        sec: 'CPG 2.A',
        label: 'Asset Inventory',
        ref: 'Up-to-date inventory of all hardware and software assets',
      },
      {
        id: 'cisa-5',
        sec: 'CPG 2.B',
        label: 'KEV Remediation',
        ref: 'CISA Known Exploited Vulnerabilities catalog remediation',
      },
      {
        id: 'cisa-6',
        sec: 'CPG 2.C',
        label: 'Vulnerability Disclosure',
        ref: 'Public vulnerability disclosure policy in place',
      },
      {
        id: 'cisa-7',
        sec: 'CPG 2.D',
        label: 'Log Collection',
        ref: 'Centralized log collection: network, endpoint, application',
      },
      {
        id: 'cisa-8',
        sec: 'CPG 2.E',
        label: 'Mitigate Obsolete Tech',
        ref: 'Plan to eliminate end-of-life software and hardware',
      },
      { id: 'cisa-9', sec: 'CPG 2.F', label: 'DMARC Email Security', ref: 'DMARC policy implemented and enforced' },
      {
        id: 'cisa-10',
        sec: 'CPG 2.G',
        label: 'Cybersecurity Training',
        ref: 'Annual cybersecurity awareness training for all staff',
      },
    ],
  },
};
