import type { Vendor, AuditEntry } from '../types/vendor';
import { FW } from './frameworks';
import { buildFWControls } from '../helpers/vendors';
import type { FrameworkControl } from '../types/framework';

function mkCtrl(
  c: { id: string; sec: string; label: string; ref: string },
  status: FrameworkControl['status'],
  by?: string,
  at?: string,
): FrameworkControl {
  return { ...c, status, approvedBy: by || '', approvedAt: at || '', notes: '' };
}

export const SEED_VENDORS: Vendor[] = [
  {
    id: 'seed-1',
    company: 'Apex Digital Solutions',
    dba: '',
    contact: 'Sarah Chen',
    email: 'schen@apexdigital.com',
    category: 'Technology',
    tier: 'HIGH',
    onsite: false,
    paid: true,
    owner: 'Admin User',
    status: 'ACTIVE',
    notes: 'Primary tech vendor. CJIS addendum on file.',
    checklist: [
      {
        id: 'contract',
        label: 'Contract (MSA / SOW)',
        ref: 'Required for all vendors',
        status: 'approved',
        approvedBy: 'Admin User',
        approvedAt: 'Nov 15, 2024',
        notes: '',
      },
      {
        id: 'w9',
        label: 'W-9 Form',
        ref: 'Required for paid vendors',
        status: 'approved',
        approvedBy: 'Admin User',
        approvedAt: 'Oct 1, 2024',
        notes: '',
      },
      {
        id: 'secq',
        label: 'Security Questionnaire Lite',
        ref: 'Required for MED/HIGH tier',
        status: 'approved',
        approvedBy: 'Admin User',
        approvedAt: 'Oct 5, 2024',
        notes: '',
      },
      {
        id: 'irc',
        label: 'Incident Response Contact',
        ref: 'Required for MED/HIGH tier',
        status: 'approved',
        approvedBy: 'Admin User',
        approvedAt: 'Oct 5, 2024',
        notes: '',
      },
      {
        id: 'addendum',
        label: 'Security Addendum',
        ref: 'Required for HIGH tier',
        status: 'approved',
        approvedBy: 'Admin User',
        approvedAt: 'Nov 15, 2024',
        notes: '',
      },
      {
        id: 'evidence',
        label: 'Security Evidence',
        ref: 'Required for HIGH tier',
        status: 'pending',
        approvedBy: '',
        approvedAt: '',
        notes: 'SOC2 report requested',
      },
    ],
    documents: [
      {
        id: 'seed-doc-1',
        name: 'MSA_Apex_2024.pdf',
        type: 'Contract',
        sensitive: false,
        uploadedBy: 'Admin User',
        uploadedAt: 'Nov 15, 2024',
        expiry: '2026-11-15',
      },
      {
        id: 'seed-doc-2',
        name: 'W9_Apex_2024.pdf',
        type: 'W-9',
        sensitive: true,
        uploadedBy: 'Admin User',
        uploadedAt: 'Oct 1, 2024',
        expiry: '',
      },
    ],
    tasks: [
      { id: 'seed-task-1', text: 'Follow up on SOC2 report', done: false, due: '2026-03-15', createdBy: 'Admin User' },
      { id: 'seed-task-2', text: 'Annual addendum renewal', done: false, due: '2026-11-01', createdBy: 'Admin User' },
    ],
    riskAnswers: [true, true, false, false, true, false, false, true, false, false],
    riskDone: true,
    frameworks: ['CJIS', 'CISA'],
    frameworkData: {
      CJIS: {
        controls: FW.CJIS.controls.map((c, i) =>
          mkCtrl(c, i < 6 ? 'approved' : i === 6 ? 'pending' : 'missing', 'Admin User', i < 6 ? 'Nov 15, 2024' : ''),
        ),
      },
      CISA: {
        controls: FW.CISA.controls.map((c, i) =>
          mkCtrl(c, i < 4 ? 'approved' : i === 4 ? 'pending' : 'missing', 'Admin User', i < 4 ? 'Nov 15, 2024' : ''),
        ),
      },
    },
    auditLog: [
      { ts: 'Feb 18, 2026, 9:00 AM', actor: 'Admin User', action: 'Status changed to ACTIVE', entity: 'vendor' },
      { ts: 'Nov 15, 2024, 10:00 AM', actor: 'Admin User', action: 'Contract approved', entity: 'checklist' },
    ],
  },
  {
    id: 'seed-2',
    company: 'Meridian Law Group',
    dba: '',
    contact: 'David Park',
    email: 'dpark@meridianlaw.com',
    category: 'Legal',
    tier: 'MED',
    onsite: false,
    paid: true,
    owner: 'Admin User',
    status: 'IN_REVIEW',
    notes: 'Legal counsel. Retainer agreement.',
    checklist: [
      {
        id: 'contract',
        label: 'Contract (MSA / SOW)',
        ref: 'Required for all vendors',
        status: 'pending',
        approvedBy: '',
        approvedAt: '',
        notes: '',
      },
      {
        id: 'w9',
        label: 'W-9 Form',
        ref: 'Required for paid vendors',
        status: 'approved',
        approvedBy: 'Admin User',
        approvedAt: 'Jun 1, 2024',
        notes: '',
      },
      {
        id: 'secq',
        label: 'Security Questionnaire Lite',
        ref: 'Required for MED/HIGH tier',
        status: 'missing',
        approvedBy: '',
        approvedAt: '',
        notes: '',
      },
      {
        id: 'irc',
        label: 'Incident Response Contact',
        ref: 'Required for MED/HIGH tier',
        status: 'missing',
        approvedBy: '',
        approvedAt: '',
        notes: '',
      },
    ],
    documents: [
      {
        id: 'seed-doc-3',
        name: 'W9_Meridian_2024.pdf',
        type: 'W-9',
        sensitive: true,
        uploadedBy: 'Admin User',
        uploadedAt: 'Jun 1, 2024',
        expiry: '',
      },
    ],
    tasks: [{ id: 'seed-task-3', text: 'Send security questionnaire', done: false, due: '2026-03-01', createdBy: 'Admin User' }],
    riskAnswers: [],
    riskDone: false,
    frameworks: ['CISA'],
    frameworkData: { CISA: { controls: buildFWControls('CISA') } },
    auditLog: [{ ts: 'Jun 1, 2024, 8:00 AM', actor: 'Admin User', action: 'Vendor created', entity: 'vendor' }],
  },
  {
    id: 'seed-3',
    company: 'Swift Logistics Co.',
    dba: '',
    contact: 'Marcus Lee',
    email: 'mlee@swiftlogistics.com',
    category: 'Logistics',
    tier: 'LOW',
    onsite: true,
    paid: true,
    owner: '',
    status: 'PROSPECT',
    notes: 'Logistics partner. Onsite deliveries.',
    checklist: [
      {
        id: 'contract',
        label: 'Contract (MSA / SOW)',
        ref: 'Required for all vendors',
        status: 'missing',
        approvedBy: '',
        approvedAt: '',
        notes: '',
      },
      {
        id: 'w9',
        label: 'W-9 Form',
        ref: 'Required for paid vendors',
        status: 'missing',
        approvedBy: '',
        approvedAt: '',
        notes: '',
      },
      {
        id: 'coi',
        label: 'Certificate of Insurance (COI)',
        ref: 'Required for onsite or HIGH tier',
        status: 'missing',
        approvedBy: '',
        approvedAt: '',
        notes: '',
      },
    ],
    documents: [],
    tasks: [],
    riskAnswers: [],
    riskDone: false,
    frameworks: [],
    frameworkData: {},
    auditLog: [{ ts: 'Feb 1, 2026, 9:00 AM', actor: 'Admin User', action: 'Vendor created', entity: 'vendor' }],
  },
];

export const SEED_AUDIT: AuditEntry[] = [
  { ts: 'Feb 21, 2026, 9:05 AM', actor: 'Admin User', action: 'Session started', entity: 'session' },
  {
    ts: 'Feb 18, 2026, 9:00 AM',
    actor: 'Admin User',
    action: 'Apex Digital status changed to ACTIVE',
    entity: 'vendor',
  },
  { ts: 'Feb 1, 2026, 9:00 AM', actor: 'Admin User', action: 'Swift Logistics vendor created', entity: 'vendor' },
];
